//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelGuide.Services.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelGuide.Services.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Common_Logout {
            get {
                return ResourceManager.GetString("Common_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Common_Success {
            get {
                return ResourceManager.GetString("Common_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Nghe thuyết minh.
        /// </summary>
        public static string Detail_Listen {
            get {
                return ResourceManager.GetString("Detail_Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có nội dung thuyết minh.
        /// </summary>
        public static string Detail_NoContent {
            get {
                return ResourceManager.GetString("Detail_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Detail_Notice {
            get {
                return ResourceManager.GetString("Detail_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ■ Dừng.
        /// </summary>
        public static string Detail_Stop {
            get {
                return ResourceManager.GetString("Detail_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang ở gần địa điểm này. Đang phát thuyết minh....
        /// </summary>
        public static string Home_AutoPlay {
            get {
                return ResourceManager.GetString("Home_AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tải bản đồ.
        /// </summary>
        public static string Home_MapError {
            get {
                return ResourceManager.GetString("Home_MapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm gần bạn.
        /// </summary>
        public static string Home_Nearby {
            get {
                return ResourceManager.GetString("Home_Nearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm địa điểm....
        /// </summary>
        public static string Home_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Home_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá những vẻ đẹp xung quanh.
        /// </summary>
        public static string Home_Subtitle {
            get {
                return ResourceManager.GetString("Home_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Home_Welcome {
            get {
                return ResourceManager.GetString("Home_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ thuyết minh.
        /// </summary>
        public static string Lang_Select {
            get {
                return ResourceManager.GetString("Lang_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ.
        /// </summary>
        public static string Lang_Title {
            get {
                return ResourceManager.GetString("Lang_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ thông tin.
        /// </summary>
        public static string Login_EmptyFields {
            get {
                return ResourceManager.GetString("Login_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại.
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tài khoản?.
        /// </summary>
        public static string Login_NoAccount {
            get {
                return ResourceManager.GetString("Login_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký ngay.
        /// </summary>
        public static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập để khám phá.
        /// </summary>
        public static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔊 Nghe thuyết minh.
        /// </summary>
        public static string Map_ListenButton {
            get {
                return ResourceManager.GetString("Map_ListenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tải bản đồ.
        /// </summary>
        public static string Map_LoadError {
            get {
                return ResourceManager.GetString("Map_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string Map_Title {
            get {
                return ResourceManager.GetString("Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí của bạn.
        /// </summary>
        public static string Map_YourLocation {
            get {
                return ResourceManager.GetString("Map_YourLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm địa điểm....
        /// </summary>
        public static string PlaceList_SearchPlaceholder {
            get {
                return ResourceManager.GetString("PlaceList_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm điểm đến tiếp theo của bạn.
        /// </summary>
        public static string PlaceList_Subtitle {
            get {
                return ResourceManager.GetString("PlaceList_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khám phá địa điểm.
        /// </summary>
        public static string PlaceList_Title {
            get {
                return ResourceManager.GetString("PlaceList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị viên.
        /// </summary>
        public static string Profile_Admin {
            get {
                return ResourceManager.GetString("Profile_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ thuyết minh.
        /// </summary>
        public static string Profile_ChangeLanguage {
            get {
                return ResourceManager.GetString("Profile_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thông tin.
        /// </summary>
        public static string Profile_EditInfo {
            get {
                return ResourceManager.GetString("Profile_EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập họ tên mới:.
        /// </summary>
        public static string Profile_EditPrompt {
            get {
                return ResourceManager.GetString("Profile_EditPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Profile_EditTitle {
            get {
                return ResourceManager.GetString("Profile_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Profile_Email {
            get {
                return ResourceManager.GetString("Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên:.
        /// </summary>
        public static string Profile_FullName {
            get {
                return ResourceManager.GetString("Profile_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ:.
        /// </summary>
        public static string Profile_Language {
            get {
                return ResourceManager.GetString("Profile_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chuyển sang.
        /// </summary>
        public static string Profile_LanguageChanged {
            get {
                return ResourceManager.GetString("Profile_LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Profile_Logout {
            get {
                return ResourceManager.GetString("Profile_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn đăng xuất?.
        /// </summary>
        public static string Profile_LogoutConfirm {
            get {
                return ResourceManager.GetString("Profile_LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Profile_LogoutTitle {
            get {
                return ResourceManager.GetString("Profile_LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string Profile_Settings {
            get {
                return ResourceManager.GetString("Profile_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du khách.
        /// </summary>
        public static string Profile_Tourist {
            get {
                return ResourceManager.GetString("Profile_Tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật thông tin.
        /// </summary>
        public static string Profile_UpdateSuccess {
            get {
                return ResourceManager.GetString("Profile_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Quay lại đăng nhập.
        /// </summary>
        public static string Register_BackToLogin {
            get {
                return ResourceManager.GetString("Register_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ thông tin bắt buộc.
        /// </summary>
        public static string Register_EmptyFields {
            get {
                return ResourceManager.GetString("Register_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thất bại.
        /// </summary>
        public static string Register_Failed {
            get {
                return ResourceManager.GetString("Register_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Register_FullName {
            get {
                return ResourceManager.GetString("Register_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu *.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản mới.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập *.
        /// </summary>
        public static string Register_Username {
            get {
                return ResourceManager.GetString("Register_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Tab_Home {
            get {
                return ResourceManager.GetString("Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        public static string Tab_Places {
            get {
                return ResourceManager.GetString("Tab_Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cá nhân.
        /// </summary>
        public static string Tab_Profile {
            get {
                return ResourceManager.GetString("Tab_Profile", resourceCulture);
            }
        }
    }
}
