//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelGuide.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelGuide.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử lại.
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Common_Success {
            get {
                return ResourceManager.GetString("Common_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung thuyết minh.
        /// </summary>
        public static string Content_Section {
            get {
                return ResourceManager.GetString("Content_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có gian hàng nào.
        /// </summary>
        public static string Home_Empty {
            get {
                return ResourceManager.GetString("Home_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào 👋.
        /// </summary>
        public static string Home_Greeting {
            get {
                return ResourceManager.GetString("Home_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gian hàng gần đây.
        /// </summary>
        public static string Home_Nearby {
            get {
                return ResourceManager.GetString("Home_Nearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn để quét gian hàng.
        /// </summary>
        public static string Home_ScanHint {
            get {
                return ResourceManager.GetString("Home_ScanHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ thuyết minh.
        /// </summary>
        public static string Lang_Select {
            get {
                return ResourceManager.GetString("Lang_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ qua, tiếp tục bằng Tiếng Việt.
        /// </summary>
        public static string Lang_Skip {
            get {
                return ResourceManager.GetString("Lang_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ thông tin..
        /// </summary>
        public static string Login_EmptyFields {
            get {
                return ResourceManager.GetString("Login_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại.
        /// </summary>
        public static string Login_Failed {
            get {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lần đầu sử dụng? Hãy chọn ngôn ngữ.
        /// </summary>
        public static string Login_FirstTime {
            get {
                return ResourceManager.GetString("Login_FirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục không cần đăng nhập.
        /// </summary>
        public static string Login_Guest {
            get {
                return ResourceManager.GetString("Login_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hoặc.
        /// </summary>
        public static string Login_OrLabel {
            get {
                return ResourceManager.GetString("Login_OrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đến nơi!.
        /// </summary>
        public static string Map_Arrived {
            get {
                return ResourceManager.GetString("Map_Arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tính đường....
        /// </summary>
        public static string Map_CalcRoute {
            get {
                return ResourceManager.GetString("Map_CalcRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tải bản đồ. Vui lòng thử lại..
        /// </summary>
        public static string Map_ErrorLoad {
            get {
                return ResourceManager.GetString("Map_ErrorLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe máy.
        /// </summary>
        public static string Map_Motorbike {
            get {
                return ResourceManager.GetString("Map_Motorbike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dẫn đường.
        /// </summary>
        public static string Map_Navigate {
            get {
                return ResourceManager.GetString("Map_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng dẫn đường.
        /// </summary>
        public static string Map_NavigateStop {
            get {
                return ResourceManager.GetString("Map_NavigateStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string Map_Title {
            get {
                return ResourceManager.GetString("Map_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí của bạn.
        /// </summary>
        public static string Map_UserLocation {
            get {
                return ResourceManager.GetString("Map_UserLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 Xem chi tiết.
        /// </summary>
        public static string Map_ViewDetail {
            get {
                return ResourceManager.GetString("Map_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đi bộ.
        /// </summary>
        public static string Map_Walk {
            get {
                return ResourceManager.GetString("Map_Walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        public static string Profile_AccountInfo {
            get {
                return ResourceManager.GetString("Profile_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị viên.
        /// </summary>
        public static string Profile_Admin {
            get {
                return ResourceManager.GetString("Profile_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi ngôn ngữ.
        /// </summary>
        public static string Profile_ChangeLanguage {
            get {
                return ResourceManager.GetString("Profile_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách (chưa đăng nhập).
        /// </summary>
        public static string Profile_Guest {
            get {
                return ResourceManager.GetString("Profile_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ thuyết minh.
        /// </summary>
        public static string Profile_Language {
            get {
                return ResourceManager.GetString("Profile_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt ngôn ngữ.
        /// </summary>
        public static string Profile_LanguageSection {
            get {
                return ResourceManager.GetString("Profile_LanguageSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập để lưu ngôn ngữ trên server.
        /// </summary>
        public static string Profile_LoginHint {
            get {
                return ResourceManager.GetString("Profile_LoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập ngay.
        /// </summary>
        public static string Profile_LoginPrompt {
            get {
                return ResourceManager.GetString("Profile_LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Profile_Logout {
            get {
                return ResourceManager.GetString("Profile_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn đăng xuất?.
        /// </summary>
        public static string Profile_LogoutConfirm {
            get {
                return ResourceManager.GetString("Profile_LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        public static string Profile_RoleField {
            get {
                return ResourceManager.GetString("Profile_RoleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách tham quan.
        /// </summary>
        public static string Profile_Tourist {
            get {
                return ResourceManager.GetString("Profile_Tourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string Profile_UsernameField {
            get {
                return ResourceManager.GetString("Profile_UsernameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có tài khoản?.
        /// </summary>
        public static string Register_AlreadyHave {
            get {
                return ResourceManager.GetString("Register_AlreadyHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản.
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        public static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        public static string Register_Placeholder_Confirm {
            get {
                return ResourceManager.GetString("Register_Placeholder_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ít nhất 6 ký tự.
        /// </summary>
        public static string Register_Placeholder_Password {
            get {
                return ResourceManager.GetString("Register_Placeholder_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên đăng nhập.
        /// </summary>
        public static string Register_Placeholder_Username {
            get {
                return ResourceManager.GetString("Register_Placeholder_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản mới.
        /// </summary>
        public static string Register_Subtitle {
            get {
                return ResourceManager.GetString("Register_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản thành công!.
        /// </summary>
        public static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét gian hàng khác.
        /// </summary>
        public static string Scan_Again {
            get {
                return ResourceManager.GetString("Scan_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng camera vào mã QR tại gian hàng.
        /// </summary>
        public static string Scan_Instruction {
            get {
                return ResourceManager.GetString("Scan_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhận diện được gian hàng. Vui lòng thử lại..
        /// </summary>
        public static string Scan_InvalidQR {
            get {
                return ResourceManager.GetString("Scan_InvalidQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải thông tin....
        /// </summary>
        public static string Scan_Loading {
            get {
                return ResourceManager.GetString("Scan_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin gian hàng..
        /// </summary>
        public static string Scan_NotFound {
            get {
                return ResourceManager.GetString("Scan_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại tuyến - không có dữ liệu. Vui lòng kết nối mạng..
        /// </summary>
        public static string Scan_Offline {
            get {
                return ResourceManager.GetString("Scan_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📷 Mở camera quét QR.
        /// </summary>
        public static string Scan_OpenCamera {
            get {
                return ResourceManager.GetString("Scan_OpenCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét mã QR.
        /// </summary>
        public static string Scan_Title {
            get {
                return ResourceManager.GetString("Scan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Tab_Home {
            get {
                return ResourceManager.GetString("Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string Tab_Map {
            get {
                return ResourceManager.GetString("Tab_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string Tab_Profile {
            get {
                return ResourceManager.GetString("Tab_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét QR.
        /// </summary>
        public static string Tab_Scan {
            get {
                return ResourceManager.GetString("Tab_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có nội dung thuyết minh.
        /// </summary>
        public static string TTS_NoContent {
            get {
                return ResourceManager.GetString("TTS_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏸ Tạm dừng.
        /// </summary>
        public static string TTS_Pause {
            get {
                return ResourceManager.GetString("TTS_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Phát thuyết minh.
        /// </summary>
        public static string TTS_Play {
            get {
                return ResourceManager.GetString("TTS_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎵 Đang phát thuyết minh....
        /// </summary>
        public static string TTS_Playing {
            get {
                return ResourceManager.GetString("TTS_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Tiếp tục.
        /// </summary>
        public static string TTS_Resume {
            get {
                return ResourceManager.GetString("TTS_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎙 Thuyết minh.
        /// </summary>
        public static string TTS_Section {
            get {
                return ResourceManager.GetString("TTS_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏹.
        /// </summary>
        public static string TTS_Stop {
            get {
                return ResourceManager.GetString("TTS_Stop", resourceCulture);
            }
        }
    }
}
